### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by MichaelAxtmann** [refresh-bio/RADULS#1]
Hello,

I would like to compare your algorithm with my sorting algorithm. Unfortunately, you did not add a license to your repository.

Note that github only grants the right to viewing and forking of unlicensed code. As far as I know, we are not allowed to change or even compile your code.

It would be awesome if you could add a license. Perhaps a license which does not allow industrial usage :)

Best

**Comment by marekkokot** [comment]
Hi,

the license have been added. Sorry for the late response. In case of any trouble let me know. 

Best regards,
Marek Kokot
